name: publish

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'

jobs:
  linux_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [ 8.0 ]

    timeout-minutes: 240

    name: Publisher

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer install --no-dev

      - name: Build stock price
        run: php pastock build:stock:price -vvv --random --full-limit=1

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: pastock/stock
          publish_branch: main
          publish_dir: ./build
          enable_jekyll: false
